name: 编译安卓APK
on: [push]

# 解决Node20的弃用警告，强制使用新的Node24环境
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取源码
        uses: actions/checkout@v5 # 升级到支持Node24的新版本

      - name: 配置JDK
        uses: actions/setup-java@v5 # 升级到支持Node24的新版本
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 自动配置Gradle环境
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.2 # 自动下载我们需要的Gradle版本，不用本地脚本

      - name: 执行编译
        run: gradle assembleDebug

      - name: 上传编译好的APK
        uses: actions/upload-artifact@v4
        with:
          name: 儿童时间管理APK
          path: app/build/outputs/apk/debug/app-debug.apk
